name: easy_alert
description: A alert package to use alert and toast within one line code.
version: 0.0.7
author: JZoom <jzoom8112@gmail.com>
homepage: https://github.com/jzoom/easy_alert

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
